### ISSUE TITLE
ips calculation error

### ISSUE THREAD

**Issue by maciekpoplawski** [papuSpartan/stable-diffusion-webui-distributed#14] opened 2023-07-21 11:37 UTC
Idk if it's an error or on purpose. 
Master is doing 60it and slave 80it. 
![image](https://github.com/papuSpartan/stable-diffusion-webui-distributed/assets/54249329/3694c37e-ed76-4cf8-a5cd-2b160b3995f3)

both run on same gpu, both have same it/s when generating on single mode.

**Comment by papuSpartan** [comment] 2023-07-21 14:21
It looks like the benchmark issue in #11 and I'll have it fixed soon. For now, you can manually edit workers.json to change the recorded speed if you wish to. I will say though, if you're running both instances off of the same accelerator/gpu, you probably won't get any benefit out of using this extension.

**Comment by maciekpoplawski** [comment] 2023-07-21 14:23
I just did the trick with workers.json :) works good. Btw it's just reversed ssh to the host pc. Extension is needed and works GREAT.

**Comment by papuSpartan** [comment] 2023-12-22 09:02
The model load difference issue should be fixed by https://github.com/papuSpartan/stable-diffusion-webui-distributed/commit/a047ab832d24a73044237a0a156033626240906a. Reopen if needed

**Closed by papuSpartan** 2023-12-22 09:02 UTC

**Comment by papuSpartan** [comment] 2023-12-22 09:04
Duplicate of #11. Should be fixed by https://github.com/papuSpartan/stable-diffusion-webui-distributed/commit/a047ab832d24a73044237a0a156033626240906a
